export default {
  FETCH_PRODUCTS: 'FETCH_PRODUCTS',
  FETCH_PRODUCTS_SUCCESS: 'FETCH_PRODUCTS_SUCCESS',
  FETCH_PRODUCTS_FAILED: 'FETCH_PRODUCTS_FAILED',
  VOTE: 'VOTE',
  VOTE_SUCCESS: 'VOTE_SUCCESS',
  VOTE_FAILED: 'VOTE_FAILED',
};
